"use client";
import {useState} from 'react';
import {lessons} from '@/lib/course';
export function normalizeAnswer(text:string){return text.normalize('NFC').toLowerCase().replace(/[।.!?·]/g,'').replace(/\s+/g,' ').trim();}
export default function Practice({lesson,onLesson}:{lesson:number;onLesson:(n:number)=>void}){
 const [scope,setScope]=useState('current'),[mode,setMode]=useState('cards'),[position,setPosition]=useState(0),[revealed,setRevealed]=useState(false),[answer,setAnswer]=useState(''),[checked,setChecked]=useState(false),[known,setKnown]=useState<string[]>([]),[again,setAgain]=useState<string[]>([]);
 const pool=(scope==='current'?[{l:lessons[lesson],i:lesson}]:lessons.map((l,i)=>({l,i}))).flatMap(({l,i})=>l.words.map((w,j)=>({...w,lesson:i,id:`${i}:${j}`})));
 const card=pool[position%pool.length],correct=[card.sa,card.roman].some(a=>normalizeAnswer(a)===normalizeAnswer(answer));
 function reset(){setPosition(0);setRevealed(false);setAnswer('');setChecked(false);setKnown([]);setAgain([]);}
 function next(){setPosition(p=>(p+1)%pool.length);setRevealed(false);setAnswer('');setChecked(false);}
 function mark(ok:boolean){setKnown(v=>ok?[...v.filter(x=>x!==card.id),card.id]:v.filter(x=>x!==card.id));setAgain(v=>ok?v.filter(x=>x!==card.id):[...v.filter(x=>x!==card.id),card.id]);next();}
 return <div className="workspace"><section className="panel"><span className="eyebrow">REVISION</span><h2>Recall before you reveal</h2><div className="practicefilters"><label>Study set<select value={scope} onChange={e=>{setScope(e.target.value);reset();}}><option value="current">Current lesson</option><option value="all">Full course</option></select></label><label>Exercise<select value={mode} onChange={e=>{setMode(e.target.value);reset();}}><option value="cards">Flashcards</option><option value="write">Write the Sanskrit</option></select></label></div><p className="small">Example {position%pool.length+1} of {pool.length} · {lessons[card.lesson].title}</p><div className="wordhero"><span lang={mode==='cards'?'sa':'en'}>{mode==='cards'?card.sa:card.english}</span>{mode==='cards'&&revealed&&<><p>{card.roman}</p><small>{card.english}</small></>}</div>{mode==='cards'?<>{!revealed?<button className="primary" onClick={()=>setRevealed(true)}>Reveal meaning</button>:<><p>{card.tip}</p><div className="actions"><button className="secondary" onClick={()=>mark(false)}>Review again</button><button className="primary" onClick={()=>mark(true)}>I remembered it</button></div></>}</>:<form onSubmit={e=>{e.preventDefault();setChecked(true);}}><label htmlFor="practice-answer">Write in Devanagari or IAST</label><input id="practice-answer" className="practiceinput" value={answer} onChange={e=>{setAnswer(e.target.value);setChecked(false);}} autoComplete="off" spellCheck={false} maxLength={200}/><p className="small">Keep vowel length and diacritics: ā, ī, ū, ṭ, ṃ, ś, ḥ. Punctuation is optional.</p><div className="actions"><button className="primary" disabled={!answer.trim()}>Check answer</button><button type="button" className="secondary" onClick={()=>setChecked(true)}>Show answer</button></div>{checked&&<div className="answerfeedback" role="status"><strong>{answer.trim()?(correct?'Correct.':'Compare with the expected form.'):'Expected form'}</strong><p lang="sa">{card.sa}</p><p>{card.roman} — {card.english}</p><small>Checks the lesson’s exact form; other valid Sanskrit expressions may exist.</small><div className="actions"><button type="button" className="secondary" onClick={next}>Next example</button></div></div>}</form>}<button className="textbutton" onClick={next}>Skip example</button></section><aside className="panel"><span className="eyebrow">REVISION ROUND</span><h2>Revision notes</h2><div className="statrow"><span>Remembered</span><strong>{known.length}</strong></div><div className="statrow"><span>Marked for review</span><strong>{again.length}</strong></div><p className="small">Use these marks to plan your next review. Quiz results appear in your overview.</p>{again.length>0&&<div className="reviewlist">{pool.filter(c=>again.includes(c.id)).map(c=><div key={c.id}><strong lang="sa">{c.sa}</strong><small>{c.roman} · {c.english}</small></div>)}</div>}<button className="secondary" onClick={()=>onLesson(card.lesson)}>Review this lesson</button></aside></div>;
}
