export type Word = {sa:string;roman:string;english:string;tip:string};
export type Question = {prompt:string;options:string[];answer:number;explain:string};
export type Lesson = {title:string;heading:string;intro:string;concept:string;words:Word[];questions:Question[]};
export const lessons:Lesson[]=[
 {title:"Greetings & introductions",heading:"A greeting to begin with",intro:"Start with a respectful greeting, then introduce yourself. Read the Roman transliteration while you get familiar with the script.",concept:"In mama nāma …, mama means ‘my’ and nāma means ‘name’. Replace the name with your own.",words:[
 {sa:"नमस्ते",roman:"namaste",english:"A respectful greeting",tip:"Break it into na · mas · te. The t is dental: touch the tongue near the upper teeth. Keep e steady rather than turning it into an English ‘ay’ glide."},
 {sa:"मम नाम अनिता।",roman:"mama nāma anitā.",english:"My name is Anita.",tip:"The line over ā marks a long vowel. Give nā and the final tā more time than the short a sounds."},
 {sa:"अहम्",roman:"aham",english:"I",tip:"Keep both a vowels short. End with m; do not add an extra vowel after it."}],questions:[
 {prompt:"What does नमस्ते (namaste) express?",options:["A respectful greeting","My name","Water"],answer:0,explain:"Namaste is a respectful greeting. You can use it to begin your practice conversation."},
 {prompt:"Which phrase means ‘my name’?",options:["aham","mama nāma","phalam"],answer:1,explain:"Mama means ‘my’; nāma means ‘name’. Together, mama nāma introduces your name."},
 {prompt:"What does अहम् (aham) mean?",options:["You","We","I"],answer:2,explain:"Aham is the first-person singular pronoun: ‘I’."}]},
 {title:"Vowels & clear sounds",heading:"Give each vowel its own space",intro:"Sanskrit distinguishes short and long vowels. Vowel length matters, so practice the pairs slowly before increasing your speed.",concept:"ā, ī, and ū are long vowels. Aim to hold them about twice as long as their short partners. The line is called a macron.",words:[
 {sa:"अ · आ",roman:"a · ā",english:"Short a · long ā",tip:"Use the same open vowel quality, then lengthen ā. Avoid giving both sounds the same duration."},
 {sa:"इ · ई",roman:"i · ī",english:"Short i · long ī",tip:"Keep the tongue forward and high. Hold ī longer without adding another sound."},
 {sa:"उ · ऊ",roman:"u · ū",english:"Short u · long ū",tip:"Round your lips gently. Keep ū steady and longer than u."}],questions:[
 {prompt:"What does the line over ā indicate?",options:["A silent vowel","A long vowel","A nasal consonant"],answer:1,explain:"The macron marks vowel length: ā is longer than a."},
 {prompt:"Which pair contains a short vowel followed by a long vowel?",options:["ī · i","ū · u","i · ī"],answer:2,explain:"I is short; ī is long. Practice hearing and producing the difference in duration."},
 {prompt:"How should ū compare with u in this practice?",options:["Hold it about twice as long","Say it more loudly","Leave it out"],answer:0,explain:"Length is about duration, not loudness. Hold the long vowel for about twice the short vowel’s time."}]},
 {title:"Everyday words",heading:"Words you can use every day",intro:"Learn three simple nouns. Say each word slowly, then connect its sound with the thing it names.",concept:"In phalam, ph represents an aspirated p: a p with a puff of air. It is not the English f sound.",words:[
 {sa:"जलम्",roman:"jalam",english:"Water",tip:"Use two short a vowels. End with m without adding a final ‘uh’."},
 {sa:"फलम्",roman:"phalam",english:"Fruit",tip:"Release p with a small puff of air. Do not substitute the English f sound."},
 {sa:"पुस्तकम्",roman:"pustakam",english:"Book",tip:"Practice pus · ta · kam. Keep the short vowels brief and finish with m."}],questions:[
 {prompt:"Which word means ‘water’?",options:["jalam","pustakam","phalam"],answer:0,explain:"Jalam means ‘water’. Phalam means ‘fruit’; pustakam means ‘book’."},
 {prompt:"How should ph in phalam be pronounced?",options:["As an English f","As p with a puff of air","As a silent letter"],answer:1,explain:"Ph represents an aspirated p. This breath distinction is part of Sanskrit’s consonant system."},
 {prompt:"What does पुस्तकम् (pustakam) mean?",options:["Water","Fruit","Book"],answer:2,explain:"Pustakam means ‘book’. Try saying it without adding a vowel after the final m."}]},
 {title:"Your first sentences",heading:"Put your first words together",intro:"Use simple statements to describe an action or identify an object. Say the whole sentence, then check each word.",concept:"Aham paṭhāmi means ‘I read’. In these examples, asti means ‘is’, and etat means ‘this’ for a neuter object.",words:[
 {sa:"अहं पठामि।",roman:"ahaṃ paṭhāmi.",english:"I read.",tip:"Ṭh is a retroflex t with a puff of air. Curl the tongue tip slightly back; hold ā longer than a."},
 {sa:"एतत् पुस्तकम् अस्ति।",roman:"etat pustakam asti.",english:"This is a book.",tip:"Practice etat · pustakam · asti. Keep the consonants clear before joining the words naturally."},
 {sa:"एतत् फलम् अस्ति।",roman:"etat phalam asti.",english:"This is a fruit.",tip:"Remember that ph is an aspirated p. Say the sentence with steady vowels."}],questions:[
 {prompt:"What does अहं पठामि (ahaṃ paṭhāmi) mean?",options:["I read","This is water","My name is Anita"],answer:0,explain:"Aham means ‘I’; paṭhāmi means ‘I read’. Before p, the written form here is ahaṃ."},
 {prompt:"In these sentences, what does asti mean?",options:["My","Is","Book"],answer:1,explain:"Asti is a form of the verb ‘to be’, meaning ‘is’."},
 {prompt:"Choose ‘This is a book’.",options:["mama nāma anitā","etat phalam asti","etat pustakam asti"],answer:2,explain:"Etat means ‘this’ here; pustakam means ‘book’, and asti means ‘is’."}]}
];
export function guidedHelp(text:string,lesson:number){const s=text.toLowerCase();if(/vowel|macron|long|short|ā|ī|ū/.test(s))return "A line over a vowel marks length: ā, ī, and ū are long. Practice a–ā, i–ī, and u–ū, holding each long vowel about twice as long. Length means duration, not extra loudness. Try lesson 2 for examples.";if(/aspirat|phalam|fruit|puff|\bph\b/.test(s))return "In phalam (फलम्, fruit), ph is a p with a puff of air. It is not the English f. Put a hand near your mouth and compare pa with pha. The tongue and lips make the same stop; the extra breath changes the sound.";if(/hello|greet|namaste/.test(s))return "नमस्ते — namaste — is a respectful greeting. Say na · mas · te, with the tongue near the upper teeth for t and a steady e. Start with namaste, then add मम नाम … — mama nāma … — ‘My name is …’.";if(/name|introduc/.test(s))return "मम नाम अनिता। — mama nāma anitā. — ‘My name is Anita.’ Mama means ‘my’; nāma means ‘name’. Replace Anita with your own name. Keep the long ā in nāma distinct from a.";if(/read|sentence|asti|paṭh/.test(s))return "अहं पठामि। — ahaṃ paṭhāmi. — ‘I read.’ Another example is एतत् पुस्तकम् अस्ति। — etat pustakam asti. — ‘This is a book.’ Practice each word slowly, then say the full sentence.";if(/water|book|word|vocab/.test(s))return "Here are three words: जलम् — jalam — water; फलम् — phalam — fruit; पुस्तकम् — pustakam — book. Keep the final m clear without adding a vowel after it. In phalam, ph is an aspirated p.";if(/help|lesson|explain|practice/.test(s))return lessons[lesson].intro+"\n\n"+lessons[lesson].concept;return "Guided mode covers the course’s greetings, vowel length, aspiration, vocabulary, and first sentences. Try ‘Explain long vowels’ or ‘Help me introduce myself’. Open-ended AI conversations will become available after the AI service is connected.";}
