"use client";
import Link from 'next/link';
import {useState,type FormEvent} from 'react';
import {requestJson,requestError} from '@/lib/client-api';
export default function Login(){
 const [register,setRegister]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{await requestJson('/api/auth/'+(register?'register':'login'),{email,password});window.location.assign('/');}catch(e){setError(requestError(e));setBusy(false);}}
 return <main className="loginpage"><Link className="brand" href="/"><span className="brandmark" lang="sa">अ</span><span>Sanskrit Path<small>Sanskrit for beginners</small></span></Link><section className="loginpanel"><h1>{register?'Create your account':'Sign in'}</h1><p>{register?'Save your progress as you learn.':'Continue where you left off.'}</p><form onSubmit={submit}><label htmlFor="email">Email</label><input id="email" type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} disabled={busy}/><label htmlFor="password">Password</label><input id="password" type="password" autoComplete={register?'new-password':'current-password'} required minLength={10} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} disabled={busy}/>{register&&<small>Use at least 10 characters.</small>}{error&&<p className="autherror" role="alert">{error}</p>}<button className="primary logincontinue" disabled={busy} type="submit">{busy?'Please wait…':register?'Create account':'Sign in'}</button></form><button className="loginbrowse" disabled={busy} onClick={()=>{setRegister(!register);setError('');setPassword('');}}>{register?'Already have an account? Sign in':'New here? Create an account'}</button><Link className="loginbrowse" href="/">Browse lessons</Link></section><p className="loginbottom">8 units · 32 lessons · Practice at your own pace</p></main>;
}
